name: Reading Comprehension Train
id:
category: Machine Learning\Train
description: Trains a Bert/Xlnet model in a supervised manner
inputs:
- name: Train data file
  type: TabularDataFolder
  port: True
  description: Training data
- name: Model type
  default: bert
  type: String
  description: Model type
- name: Model name
  default: bert-large-uncased-whole-word-masking
  type: String
  description: Model name
- name: Max seq Length
  default: 50
  type: Int
  description: Max seq Length
- name: Batch size
  default: 32
  type: Int
  description: Batch size
- name: Learning rate
  default: 0.1
  type: Float
  description: Learning rate
- name: Epoch num
  default: 1
  type: Int
  description: Epoch num
outputs:
- name: Trained model
  type: ModelFolder
  description: Trained learner
implementation:
  container:
    runConfig:
      baseDockerImage: mcr.microsoft.com/azureml/base-gpu:intelmpi2018.3-cuda10.0-cudnn7-ubuntu16.04
      gpuSupport: true
    conda:
      name: project_environment
      channels:
      - defaults
      dependencies:
      - python=3.6.8
      - pip:
        - --extra-index-url=https://test.pypi.org/simple
        - alghost==0.0.53
        - pyarrow==0.12.1
        - numpy==1.16.2
        - pandas==0.24.1
        - pytorch-transformers==1.0.0
        - https://download.pytorch.org/whl/cu100/torch-1.1.0-cp36-cp36m-linux_x86_64.whl
        - torchvision==0.2.2.post3
        - git+https://github.com/Angeliacs/azureml-custom-module-examples.git@chsi/Bert-QA#subdirectory=QA
    command:
    - python
    - -m
    - examples.train
    - --do_lower_case
    args:
    - --model_type
    - inputValue: Model type
    - --model_name_or_path
    - inputValue: Model name
    - --max_seq_length
    - inputValue: Max seq Length
    - --train_file
    - inputValue: Train data file
    - --learning_rate
    - inputValue: Learning rate
    - --num_train_epochs
    - inputValue: Epoch num
    - --per_gpu_train_batch_size
    - inputValue: Batch size
    - --output_dir
    - outputPath: Trained model
